{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "vnp.fullname" . }}
  namespace: {{ .Values.namespace | quote }}
  annotations: 
    volume.beta.kubernetes.io/storage-provisioner: cephfs.csi.ceph.com
spec:
  accessModes:
  {{- if not (empty .Values.persistence.accessModes) }}
  {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  {{- else }}
    - {{ .Values.persistence.accessMode | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  volumeMode: {{ .Values.persistence.volumeMode | quote }}
{{- end -}}
