apiVersion: v1
kind: Service
metadata:
  name: {{ include "vnp.fullname" . }}
  namespace: {{ .Values.namespace | quote }}
  labels:
    {{- include "vnp.labels" . | nindent 4 }}
  annotations:
    ovn.kubernetes.io/vpc: ovn-cluster
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5555
      protocol: TCP
      name: mjcwbr
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePorts.vnp)) }}
      nodePort: {{ .Values.service.nodePorts.vnp }}
      {{- else if eq .Values.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
  selector:
    {{- include "vnp.selectorLabels" . | nindent 4 }}
